return {
{
title = "RC Standard",
id = 'RCMetadataSetOne',
items = {
{ "com.adobe.label", label = "File Info" },
'com.adobe.filename',
'com.adobe.originalFilename.ifDiffers',
'com.adobe.sidecars',
'com.adobe.copyname',
'com.adobe.folder',
'com.adobe.filesize',
'com.adobe.filetype',
'com.adobe.fileFormat',
'com.adobe.dateTime.onlyIfUnique',
'com.adobe.dateTimeOriginal',
'com.adobe.dateTimeDigitized.onlyIfUnique',
'com.adobe.colorLabels',
'com.adobe.metadataStatus',
'com.adobe.metadataDate',
'com.adobe.audioAnnotation',
'com.adobe.imageFileDimensions',
'com.adobe.imageCroppedDimensions',
'com.adobe.separator',
{ "com.adobe.label", label = "Title & Caption" },
'com.adobe.title',
{ 'com.adobe.caption', height_in_lines = 3 },
'com.adobe.separator',
{ "com.adobe.label", label = "Shooting Info" },
'com.adobe.shutterSpeedValue',
'com.adobe.apertureValue',
'com.adobe.brightnessValue',
'com.adobe.exposureBiasValue',
'com.adobe.flash',
'com.adobe.exposureProgram',
'com.adobe.meteringMode',
'com.adobe.ISOSpeedRating',
'com.adobe.focalLength',
'com.adobe.focalLength35mm',
'com.adobe.lens',
'com.adobe.subjectDistance',
'com.adobe.make',
'com.adobe.model',
'com.adobe.serialNumber',
'com.adobe.artist',
'com.adobe.software',
'com.adobe.separator',
{ "com.adobe.label", label = "Creator" },
'com.adobe.creator',
'com.adobe.creatorJobTitle',
'com.adobe.creatorWorkWebsite',
'com.adobe.separator',
{ "com.adobe.label", label = "Genre, Scene, & Location" },
'com.adobe.intellectualGenre',
'com.adobe.scene',
'com.adobe.location',
'com.adobe.city',
'com.adobe.state',
'com.adobe.country',
'com.adobe.isoCountryCode',
'com.robcole.lightroom.CustomMetadata.*',
'com.robcole.dev.ChangeManager.*',
'com.robcole.lightroom.ChangeManager.*',
'com.robcole.lightroom.metadata.RC_CustomMetadata.*',
'com.robcole.lightroom.develop.DevAdjust.*',
'com.adobe.separator',
{ "com.adobe.label", label = "RC Dev Meta" },
'com.adobe.separator',
'com.robcole.DevMeta.lastUpdate',
'com.adobe.separator',
'com.robcole.DevMeta.ProcessVersion',
'com.adobe.separator',
{ "com.adobe.label", label = "Camera Calibration" },
'com.robcole.DevMeta.CameraProfile',
'com.robcole.DevMeta.ShadowTint',
'com.robcole.DevMeta.rgbColorMods',
'com.adobe.separator',
{ "com.adobe.label", label = "Basic" },
'com.robcole.DevMeta.WhiteBalance',
'com.robcole.DevMeta.Temperature',
'com.robcole.DevMeta.Tint',
'com.adobe.separator',
'com.robcole.DevMeta.Exposure2012',
'com.robcole.DevMeta.Contrast2012',
'com.robcole.DevMeta.Highlights2012',
'com.robcole.DevMeta.Shadows2012',
'com.robcole.DevMeta.Whites2012',
'com.robcole.DevMeta.Blacks2012',
'com.robcole.DevMeta.Clarity2012',
'com.adobe.separator',
'com.robcole.DevMeta.Vibrance',
'com.robcole.DevMeta.Saturation',
'com.adobe.separator',
'com.robcole.DevMeta.Exposure',
'com.robcole.DevMeta.HighlightRecovery',
'com.robcole.DevMeta.FillLight',
'com.robcole.DevMeta.Shadows',
'com.robcole.DevMeta.Brightness',
'com.robcole.DevMeta.Contrast',
'com.robcole.DevMeta.Clarity',
'com.adobe.separator',
{ "com.adobe.label", label = "Tone Curve" },
'com.robcole.DevMeta.ToneCurveName',
'com.robcole.DevMeta.toneCurveParamMods',
'com.robcole.DevMeta.toneCurvePointMods',
'com.robcole.DevMeta.channelCurveMods',
'com.adobe.separator',
{ "com.adobe.label", label = "HSL / Color / B & W" },
'com.robcole.DevMeta.colorType',
'com.robcole.DevMeta.colorMods',
'com.adobe.separator',
{ "com.adobe.label", label = "Split Toning" },
'com.robcole.DevMeta.splitToning',
'com.adobe.separator',
{ "com.adobe.label", label = "Detail" },
'com.robcole.DevMeta.Sharpness',
'com.robcole.DevMeta.SharpenRadius',
'com.robcole.DevMeta.SharpenDetail',
'com.robcole.DevMeta.SharpenEdgeMasking',
'com.adobe.separator',
'com.robcole.DevMeta.LuminanceSmoothing',
'com.robcole.DevMeta.LuminanceNoiseReductionDetail',
'com.robcole.DevMeta.LuminanceNoiseReductionContrast',
'com.adobe.separator',
'com.robcole.DevMeta.ColorNoiseReduction',
'com.robcole.DevMeta.ColorNoiseReductionDetail',
'com.adobe.separator',
{ "com.adobe.label", label = "Lens Corrections" },
'com.robcole.DevMeta.lensDistortion',
'com.robcole.DevMeta.lensVignetting',
'com.robcole.DevMeta.lensCa',
'com.robcole.DevMeta.perspective',
'com.adobe.separator',
{ "com.adobe.label", label = "Effects" },
'com.robcole.DevMeta.postCropVignette',
'com.robcole.DevMeta.grain',
'com.adobe.separator',
{ "com.adobe.label", label = "Crop, Locals, & Retouch" },
'com.robcole.DevMeta.CropWidth',
'com.robcole.DevMeta.CropHeight',
'com.robcole.DevMeta.retouched',
'com.robcole.DevMeta.redeye',
'com.robcole.DevMeta.gradients',
'com.robcole.DevMeta.brushes',
'com.adobe.separator',
'com.robcole.DevMeta.stackPos',
'com.robcole.DevMeta.pixelCount',
'com.robcole.DevMeta.aspectRatio',
'com.robcole.lightroom.NxToo.*',
'com.robcole.lightroom.plugin.nxTooey3.*',
'com.adobe.separator',
{"com.adobe.label", label="RC Exif Meta" },
'com.adobe.separator',
'cz.geokuk.lightroom.LoadGpsData.lastUpdate',
'com.adobe.separator',
{ 'com.adobe.label', label = 'Composite' },
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSAltitude',
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSDateTime',
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSLatitude',
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSLongitude',
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSPosition',
{ 'com.adobe.label', label = 'GPS' },
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSAltitude',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSAltitudeRef',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSDateStamp',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSLatitude',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSLatitudeRef',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSLongitude',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSLongitudeRef',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSMapDatum',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSSatellites',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSTimeStamp',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSVersionID',
'com.adobe.separator',
{ formatter = 'cz.geokuk.lightroom.LoadGpsData.bigBlock', topLabel=true },
},
},
{
title = "RC Custom",
id = 'RCMetadataSetTwo',
items = {
'com.adobe.filename',
'com.adobe.separator',
{"com.adobe.label", label="RC Exif Meta" },
'com.adobe.separator',
'cz.geokuk.lightroom.LoadGpsData.lastUpdate',
'com.adobe.separator',
{ 'com.adobe.label', label = 'Composite' },
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSAltitude',
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSDateTime',
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSLatitude',
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSLongitude',
'cz.geokuk.lightroom.LoadGpsData.Composite_GPSPosition',
{ 'com.adobe.label', label = 'GPS' },
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSAltitude',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSAltitudeRef',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSDateStamp',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSLatitude',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSLatitudeRef',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSLongitude',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSLongitudeRef',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSMapDatum',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSSatellites',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSTimeStamp',
'cz.geokuk.lightroom.LoadGpsData.GPS_GPSVersionID',
'com.adobe.separator',
{ formatter = 'cz.geokuk.lightroom.LoadGpsData.bigBlock', topLabel=true },
},
},
}